
CREATE TABLE tCardapio (
                IDCARDAPIO BIGINT AUTO_INCREMENT NOT NULL,
                NOME VARCHAR NOT NULL,
                DESCRICAO VARCHAR,
                PRIMARY KEY (IDCARDAPIO)
);


CREATE TABLE tMesa (
                IDMESA INT AUTO_INCREMENT NOT NULL,
                STATUS CHAR NOT NULL,
                PRIMARY KEY (IDMESA)
);


CREATE TABLE tCabPedido (
                IDPED BIGINT AUTO_INCREMENT NOT NULL,
                IDMESA INT NOT NULL,
                VLRTOT DOUBLE PRECISIONS DEFAULT 0 NOT NULL,
                VLRDESC DOUBLE PRECISIONS DEFAULT 0 NOT NULL,
                PRIMARY KEY (IDPED, IDMESA)
);


CREATE TABLE tItensPedido (
                IDPED BIGINT NOT NULL,
                IDMESA INT NOT NULL,
                SEQUENCIA INT AUTO_INCREMENT NOT NULL,
                IDCARDAPIO BIGINT NOT NULL,
                TAMANHO VARCHAR NOT NULL,
                QUANTIDADE DOUBLE PRECISIONS DEFAULT 1 NOT NULL,
                VLRUNIT DOUBLE PRECISIONS NOT NULL,
                VLRDESCITE DOUBLE PRECISIONS DEFAULT 0,
                VLRTOT DOUBLE PRECISIONS DEFAULT 0 NOT NULL,
                PRIMARY KEY (IDPED, IDMESA, SEQUENCIA, IDCARDAPIO)
);


CREATE TABLE tProdutos (
                IDPROD INT AUTO_INCREMENT NOT NULL,
                Nome VARCHAR NOT NULL,
                ESTMIN DOUBLE PRECISIONS NOT NULL,
                PRIMARY KEY (IDPROD)
);

ALTER TABLE tProdutos COMMENT 'Tabela de Materias primas';


CREATE TABLE tComponentes (
                IDCARDAPIO BIGINT NOT NULL,
                IDPROD INT NOT NULL,
                QUANTIDADE DOUBLE PRECISIONS NOT NULL,
                PRIMARY KEY (IDCARDAPIO, IDPROD)
);


CREATE TABLE tEstoque (
                IDPROD INT NOT NULL,
                ESTOQUE DOUBLE PRECISIONS,
                VALIDADE DATE,
                PRIMARY KEY (IDPROD)
);


ALTER TABLE tComponentes ADD CONSTRAINT tcardapio_tcomponentes_fk
FOREIGN KEY (IDCARDAPIO)
REFERENCES tCardapio (IDCARDAPIO)
ON DELETE CASCADE
ON UPDATE NO ACTION;

ALTER TABLE tItensPedido ADD CONSTRAINT tcardapio_titenspedido_fk
FOREIGN KEY (IDCARDAPIO)
REFERENCES tCardapio (IDCARDAPIO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE tCabPedido ADD CONSTRAINT tmesa_tcabpedido_fk
FOREIGN KEY (IDMESA)
REFERENCES tMesa (IDMESA)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE tItensPedido ADD CONSTRAINT tcabpedido_titenspedido_fk
FOREIGN KEY (IDMESA, IDPED)
REFERENCES tCabPedido (IDMESA, IDPED)
ON DELETE CASCADE
ON UPDATE NO ACTION;

ALTER TABLE tEstoque ADD CONSTRAINT tprodutos_testoque_fk
FOREIGN KEY (IDPROD)
REFERENCES tProdutos (IDPROD)
ON DELETE CASCADE
ON UPDATE NO ACTION;

ALTER TABLE tComponentes ADD CONSTRAINT tprodutos_tcomponentes_fk
FOREIGN KEY (IDPROD)
REFERENCES tProdutos (IDPROD)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
